import type { Metadata } from "next"
import { ReactNode } from "react"
import { ThemeProvider } from "@/components/ThemeProvider"
import { extractRouterConfig } from "uploadthing/server"
import { ourFileRouter } from "./api/uploadthing/core"
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin"
import { Toaster } from "sonner"
import { inter } from "./fonts"
import AuthProvider from "@/components/AuthProvider"
import "./globals.css"

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app"
}

export default function RootLayout({ children }: { children: ReactNode }) {
 return (
  <html lang="en" className="dark" suppressHydrationWarning>
   <body className={inter.className}>
    <ThemeProvider
     attribute="class"
     defaultTheme="system"
     enableSystem
     disableTransitionOnChange
    >
     <AuthProvider>
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
      {children}
      <Toaster richColors />
     </AuthProvider>
    </ThemeProvider>
   </body>
  </html>
 )
}